**Creation of Arrays**
- Creating NumPy arrays using a list as a parameter to the array constructor:
  - Example: `np.array([1, 2, 3])` creates a one-dimensional array.
- Creating two-dimensional arrays by listing the rows:
  - Example: `np.array([[1, 2, 3], [4, 5, 6]])`
- Creating three-dimensional arrays as a list of lists of lists:
  - Example: `np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]])`

**Helper Functions for Common Types of Arrays**
- `np.zeros(shape, dtype=float)` initializes an array with zeros.
  - Example: `np.zeros((3, 4))`
- To specify integer elements, use the `dtype` parameter:
  - Example: `np.zeros((3, 4), dtype=int)`
- `np.ones(shape, dtype=float)` initializes an array with ones.
- `np.full(shape, fill_value, dtype=None)` initializes an array with a specified value.
- `np.empty(shape, dtype=float)` creates an array with uninitialized elements.
- `np.eye(N, M=None, k=0, dtype=float)` creates an identity matrix.

**Array Generation with Random Elements**
- Generating random data with NumPy:
  - `np.random.random(size)` creates an array of random numbers from a uniform distribution.
  - `np.random.normal(loc, scale, size)` generates random numbers from a normal distribution.
  - `np.random.randint(low, high, size)` creates an array of random integers within a given range.
- Setting a seed for reproducibility using `np.random.seed(seed)`.
- Creating a new random number generator using `np.random.RandomState(seed)`.

**Array Types and Attributes**
- Array attributes:
  - `ndim` for the number of dimensions.
  - `shape` for the size in each dimension.
  - `size` for the number of elements.
  - `dtype` for the element type.
- Example function to explore these attributes:

```python
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)
```

**Indexing, Slicing, and Reshaping**
- Indexing:
  - One-dimensional array behaves like a Python list.
  - Multi-dimensional array indexing uses a tuple of indices.
- Slicing:
  - Slicing works similarly to Python lists, and you can have slices in different dimensions.
  - Slicing and assignment to a slice are possible.
- Reshaping:
  - Reshaping an array changes its interpretation without changing the number of elements.
  - Use `reshape` or the `np.newaxis` keyword to create row or column vectors.


In [2]:
"""
Exercise 2.11 (rows and columns)
Write two functions, get_rows and get_columns, that get a two dimensional array as parameter. They should return the list of rows and columns of the array, respectively. The rows and columns should be one dimensional arrays. You may use the transpose operation, which flips rows to columns, in your solution. The transpose is done by the T method:

a=np.random.randint(0, 10, (4,4))
print(a)
print(a.T)
[[0 1 9 9]
[0 4 7 3]
[2 7 2 0]
[0 4 5 5]]
[[0 0 2 0]
[1 4 7 4]
[9 7 2 5]
[9 3 0 5]]

Test your solution in the main function. Example of usage:

a = np.array([[5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]])
get_rows(a)
[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]
get_columns(a)
[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]
"""
import numpy as np

def get_rows(a):
    return list(a)

def get_columns(a):
    return list(a.T)

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Rows:", get_rows(a))
    print("Columns:", get_columns(a))
main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Rows: [array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]
Columns: [array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]


**Concatenation:**
- Combining several arrays into a single bigger array.
- Two primary methods: `np.concatenate` and `np.stack`.
- `np.concatenate`:
  - Combines n-dimensional arrays into an n-dimensional array.
  - Example 1 (1D arrays):
    ```python
    a = np.arange(2)
    b = np.arange(2, 5)
    result = np.concatenate((a, b))
    ```
    Output:
    ```
    array([0, 1, 2, 3, 4])
    ```
  - Example 2 (2D arrays):
    ```python
    c = np.arange(1, 5).reshape(2, 2)
    result = np.concatenate((c, c))
    ```
    Output:
    ```
    array([[1, 2],
           [3, 4],
           [1, 2],
           [3, 4]])
    ```
- By default, `np.concatenate` joins arrays along `axis=0`.
- To join arrays horizontally, specify `axis=1`:
  ```python
  np.concatenate((c, c), axis=1)
  ```
  Output:
  ```
  array([[1, 2, 1, 2],
         [3, 4, 3, 4])
  ```
- When concatenating arrays with different dimensions, you must first reshape them to have the same number of dimensions.

**Stacking:**
- Creating higher-dimensional arrays from lower-dimensional arrays.
- `np.stack`:
  - Takes n-dimensional arrays and returns an n+1-dimensional array.
  - Example 1 (stacking 1D arrays):
    ```python
    result = np.stack((b, b))
    ```
    Output:
    ```
    array([[2, 3, 4],
           [2, 3, 4])
    ```
  - Example 2 (stacking 1D arrays along `axis=1`):
    ```python
    result = np.stack((b, b), axis=1)
    ```
    Output:
    ```
    array([[2, 2],
           [3, 3],
           [4, 4])
    ```

**Splitting:**
- The inverse operation of concatenation.
- Splits an array into multiple smaller arrays.
- `np.split`:
  - Takes an array and splits it into specified parts or at explicit breakpoints.
  - Example 1 (splitting a 2D array into two equal parts):
    ```python
    d1, d2 = np.split(d, 2)
    ```
    Output:
    `d1`:
    ```
    array([[0, 1],
           [2, 3],
           [4, 5]])
    ```
    `d2`:
    ```
    array([[ 6, 7],
           [ 8, 9],
           [10, 11]])
    ```
  - Example 2 (splitting a 2D array into parts with explicit breakpoints):
    ```python
    parts = np.split(d, (2, 3, 5), axis=1)
    ```
    Output:
    `part 0`:
    ```
    [[0 1]
     [6 7]]
    ```
    `part 1`:
    ```
    [[2]
     [8]]
    ```
    `part 2`:
    ```
    [[ 3 4]
     [ 9 10]]
    ```
    `part 3`:
    ```
    [[ 5]
     [11]]
    ```

In [6]:
"""
Exercise 2.12 (row and column vectors)
Create function get_row_vectors that returns a list of rows from the input array of shape (n,m), but 
this time the rows must have shape (1,m).
Similarly, create function get_columns_vectors that returns a list of columns (each having shape (n,1)) of the input matrix .

Example: for a 2x3 input matrix

 [[5 0 3]
  [3 7 9]]
the result should be

Row vectors: 
[array([[5, 0, 3]]), array([[3, 7, 9]])]
Column vectors: 
[array([[5],
        [3]]), 
 array([[0],
        [7]]), 
 array([[3],
        [9]])]
The above output is basically just the returned lists printed with print. 
Only some whitespace is adjusted to make it look nicer. Output is not tested.
"""

import numpy as np

def get_row_vectors(a):
    n, m = a.shape
    # Use np.split to split the matrix a long axis 0 ( rows )
    # It uses the np.split() function to split the matrix a along axis 0, which corresponds to rows. 
    # This operation separates the rows of the matrix and creates a list of row vectors.
    row_vectors = np.split(a, n)

    return row_vectors

def get_column_vectors(a):
    n, m = a.shape
    # Use np.split to split the matrix a long axis 0 ( rows )
    column_vectors = np.split(a, m, axis = 1)
    return column_vectors

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Row vectors:", get_row_vectors(a))
    print("Column vectors:", get_column_vectors(a))
main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Row vectors: [array([[5, 0, 3, 3]]), array([[7, 9, 3, 5]]), array([[2, 4, 7, 6]]), array([[8, 8, 1, 6]])]
Column vectors: [array([[5],
       [7],
       [2],
       [8]]), array([[0],
       [9],
       [4],
       [8]]), array([[3],
       [3],
       [7],
       [1]]), array([[3],
       [5],
       [6],
       [6]])]


In [100]:
"""
Exercise 2.13 (diamond)
Create a function diamond that returns a two dimensional integer array where the 1s form a diamond shape. 
Rest of the numbers are 0. The function should get a parameter that tells the length of a side of the diamond. 
Do this using the eye and concatenate functions of NumPy and array slicing.

Example of usage:

print(diamond(3))
[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]
print(diamond(1))
[[1]]
"""


import numpy as np

def diamond(n):
    # eye and concatenate
    # NumPy and array slicing

    # create an eye
    top_half = np.eye(n, dtype = int)
 
  
    # flip and remove the first row
    # bottom_half = np.flip(top_half, axis = 0)[1:]

    # we flip the top half to make it bottom
    bottom_half = top_half[::-1,:]

    # we remove the first row of the bottom
    bottom_half = bottom_half[1:,:]
  
    # right side 
    # we concatenate top half and bottom half to make it the right side of the diamond
    right_side = np.concatenate((top_half, bottom_half))
    
    #left_side = np.flip(right_side, axis = 1)[:,:-1]

    # flip the right side of the diamond to make it left
    left_side = right_side[:,::-1]
    
    # then we remove the last column of the left side
    left_side = left_side[:,:-1]

    # diamond = concatenate left side and right side column or horizontal wise
    diamond = np.concatenate((left_side, right_side), axis = 1)
    return(diamond)
    
"""
def diamond(n):
    e=np.eye(n, dtype=int)
    a=np.concatenate([e[::-1], e[:,1:]], axis=1)
    result = np.concatenate([a[:-1], a[::-1]], axis=0)
    return result
"""

def main():
    result = diamond(1)
    print(result)
main()

[[1]]


**Universal Functions (ufuncs) in NumPy:**
- NumPy provides efficient routines for computations on multi-dimensional arrays.
- These computations are more efficient than Python's default operations, mainly due to the use of ufuncs.
- The biggest bottleneck in efficiency for Python is the dynamic typing of variables.

**Dynamic Typing in Python:**
- In Python, at each expression, the types of the arguments need to be determined.
- For example, in the following Python loop, the variable `x` can be an int, float, or string, which requires type checking at each iteration:
```python
L = [1, 5.2, "ab"]
L2 = []
for x in L:
    L2.append(x * 2)
```
- This dynamic typing can slow down loops, especially when iterated millions or billions of times.

**NumPy's Homogeneity:**
- NumPy requires that all elements in an array must be of the same type, ensuring homogeneity.
- This allows for vectorized operations, where operations are performed on arrays rather than individual elements.
- Vectorized operations can be compiled into machine code, improving efficiency by avoiding Python's dynamic typing.
- Example using NumPy's vectorized operation:
```python
a = np.array([2.1, 5.0, 17.2])
a2 = a * 2
```

**Basic Arithmetic Operations in NumPy:**
- NumPy supports various basic arithmetic operations, including addition, subtraction, negation, multiplication, division, floor division, exponentiation, and remainder.
- These operations can be combined to form complex expressions.
- Example:
```python
b = np.array([-1, 3.2, 2.4])
result = -a**2 * b
```

**Mathematical Functions in NumPy:**
- NumPy provides mathematical functions in vector form, including `np.abs()`, `np.cos()`, `np.exp()`, and `np.log2()`.
- Example:
```python
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b))
```

**Aggregations in NumPy:**
- Aggregations allow you to summarize information in an array into a few numbers.
- Common aggregation functions in NumPy include `min()`, `max()`, `sum()`, `mean()`, and `std()`.
- Example of aggregating an array:
```python
np.random.seed(0)
a = np.random.randint(-100, 100, (4, 5))
print(f"Minimum: {a.min()}, maximum: {a.max()}")
print(f"Sum: {a.sum()}")
print(f"Mean: {a.mean()}, standard deviation: {a.std()}")
```

**Aggregating Over Specific Axes:**
- You can aggregate over specific axes in multi-dimensional arrays.
- Example of column and row sums:
```python
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))
```

**Comparison of Python's `sum` and NumPy's `np.sum`:**
- NumPy's efficiency is partly due to the requirement of the same data type for all elements.
- Measuring the speed difference between Python's `sum` and NumPy's `np.sum`:
```python
%timeit np.sum(a)  # NumPy
%timeit sum(a)     # Python
```

NumPy's use of universal functions and array homogeneity results in significant performance improvements compared to Python's default operations.

In [114]:
"""
Exercise 2.14 (vector lengths)
Write function vector_lengths that gets a two dimensional array of shape (n,m) as a parameter. 
Each row in this array corresponds to a vector. 
The function should return an array of shape (n,), that has the length of each vector in the input. 
The length is defined by the usual Euclidean norm (Wikipedia). 

Don't use loops at all in your solution. 
Instead use vectorized operations. 
You must use at least the np.sum and the np.sqrt functions. 
You can't use the function scipy.linalg.norm. 
Test your function in the main function.
"""

import numpy as np
#import scipy.linalg

def vector_lengths(a):
    # return an array of shape (n,)
    # that has the length of each vector in the input. 
    # Euclid norm for ||V|| = sqrt(3^2 + 4^2)
    # use vectorized operations. 
    # the np.sum and the np.sqrt functions. 
    
    # square
    value  = a**2
    value = value.sum(axis=1)
    value = np.sqrt(value)


  

    return np.array(value)
"""
def vector_lengths(a):
    #return scipy.linalg.norm(a, 2, axis=1)
    return np.sqrt(np.sum(a**2, axis=1))
"""
def main():
    n=10
    for m in range(1,5):
        a=np.random.randn(n, m)
        result = vector_lengths(a)
        if result.shape == (n,):
            print(f"{result.shape}")
main()

(10,)
(10,)
(10,)
(10,)
