**Creation of Arrays**
- Creating NumPy arrays using a list as a parameter to the array constructor:
  - Example: `np.array([1, 2, 3])` creates a one-dimensional array.
- Creating two-dimensional arrays by listing the rows:
  - Example: `np.array([[1, 2, 3], [4, 5, 6]])`
- Creating three-dimensional arrays as a list of lists of lists:
  - Example: `np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]])`

**Helper Functions for Common Types of Arrays**
- `np.zeros(shape, dtype=float)` initializes an array with zeros.
  - Example: `np.zeros((3, 4))`
- To specify integer elements, use the `dtype` parameter:
  - Example: `np.zeros((3, 4), dtype=int)`
- `np.ones(shape, dtype=float)` initializes an array with ones.
- `np.full(shape, fill_value, dtype=None)` initializes an array with a specified value.
- `np.empty(shape, dtype=float)` creates an array with uninitialized elements.
- `np.eye(N, M=None, k=0, dtype=float)` creates an identity matrix.

**Array Generation with Random Elements**
- Generating random data with NumPy:
  - `np.random.random(size)` creates an array of random numbers from a uniform distribution.
  - `np.random.normal(loc, scale, size)` generates random numbers from a normal distribution.
  - `np.random.randint(low, high, size)` creates an array of random integers within a given range.
- Setting a seed for reproducibility using `np.random.seed(seed)`.
- Creating a new random number generator using `np.random.RandomState(seed)`.

**Array Types and Attributes**
- Array attributes:
  - `ndim` for the number of dimensions.
  - `shape` for the size in each dimension.
  - `size` for the number of elements.
  - `dtype` for the element type.
- Example function to explore these attributes:

```python
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)
```

**Indexing, Slicing, and Reshaping**
- Indexing:
  - One-dimensional array behaves like a Python list.
  - Multi-dimensional array indexing uses a tuple of indices.
- Slicing:
  - Slicing works similarly to Python lists, and you can have slices in different dimensions.
  - Slicing and assignment to a slice are possible.
- Reshaping:
  - Reshaping an array changes its interpretation without changing the number of elements.
  - Use `reshape` or the `np.newaxis` keyword to create row or column vectors.


In [2]:
"""
Exercise 2.11 (rows and columns)
Write two functions, get_rows and get_columns, that get a two dimensional array as parameter. They should return the list of rows and columns of the array, respectively. The rows and columns should be one dimensional arrays. You may use the transpose operation, which flips rows to columns, in your solution. The transpose is done by the T method:

a=np.random.randint(0, 10, (4,4))
print(a)
print(a.T)
[[0 1 9 9]
[0 4 7 3]
[2 7 2 0]
[0 4 5 5]]
[[0 0 2 0]
[1 4 7 4]
[9 7 2 5]
[9 3 0 5]]

Test your solution in the main function. Example of usage:

a = np.array([[5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]])
get_rows(a)
[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]
get_columns(a)
[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]
"""
import numpy as np

def get_rows(a):
    return list(a)

def get_columns(a):
    return list(a.T)

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Rows:", get_rows(a))
    print("Columns:", get_columns(a))
main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Rows: [array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]
Columns: [array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]


**Concatenation:**
- Combining several arrays into a single bigger array.
- Two primary methods: `np.concatenate` and `np.stack`.
- `np.concatenate`:
  - Combines n-dimensional arrays into an n-dimensional array.
  - Example 1 (1D arrays):
    ```python
    a = np.arange(2)
    b = np.arange(2, 5)
    result = np.concatenate((a, b))
    ```
    Output:
    ```
    array([0, 1, 2, 3, 4])
    ```
  - Example 2 (2D arrays):
    ```python
    c = np.arange(1, 5).reshape(2, 2)
    result = np.concatenate((c, c))
    ```
    Output:
    ```
    array([[1, 2],
           [3, 4],
           [1, 2],
           [3, 4]])
    ```
- By default, `np.concatenate` joins arrays along `axis=0`.
- To join arrays horizontally, specify `axis=1`:
  ```python
  np.concatenate((c, c), axis=1)
  ```
  Output:
  ```
  array([[1, 2, 1, 2],
         [3, 4, 3, 4])
  ```
- When concatenating arrays with different dimensions, you must first reshape them to have the same number of dimensions.

**Stacking:**
- Creating higher-dimensional arrays from lower-dimensional arrays.
- `np.stack`:
  - Takes n-dimensional arrays and returns an n+1-dimensional array.
  - Example 1 (stacking 1D arrays):
    ```python
    result = np.stack((b, b))
    ```
    Output:
    ```
    array([[2, 3, 4],
           [2, 3, 4])
    ```
  - Example 2 (stacking 1D arrays along `axis=1`):
    ```python
    result = np.stack((b, b), axis=1)
    ```
    Output:
    ```
    array([[2, 2],
           [3, 3],
           [4, 4])
    ```

**Splitting:**
- The inverse operation of concatenation.
- Splits an array into multiple smaller arrays.
- `np.split`:
  - Takes an array and splits it into specified parts or at explicit breakpoints.
  - Example 1 (splitting a 2D array into two equal parts):
    ```python
    d1, d2 = np.split(d, 2)
    ```
    Output:
    `d1`:
    ```
    array([[0, 1],
           [2, 3],
           [4, 5]])
    ```
    `d2`:
    ```
    array([[ 6, 7],
           [ 8, 9],
           [10, 11]])
    ```
  - Example 2 (splitting a 2D array into parts with explicit breakpoints):
    ```python
    parts = np.split(d, (2, 3, 5), axis=1)
    ```
    Output:
    `part 0`:
    ```
    [[0 1]
     [6 7]]
    ```
    `part 1`:
    ```
    [[2]
     [8]]
    ```
    `part 2`:
    ```
    [[ 3 4]
     [ 9 10]]
    ```
    `part 3`:
    ```
    [[ 5]
     [11]]
    ```

In [6]:
"""
Exercise 2.12 (row and column vectors)
Create function get_row_vectors that returns a list of rows from the input array of shape (n,m), but 
this time the rows must have shape (1,m).
Similarly, create function get_columns_vectors that returns a list of columns (each having shape (n,1)) of the input matrix .

Example: for a 2x3 input matrix

 [[5 0 3]
  [3 7 9]]
the result should be

Row vectors: 
[array([[5, 0, 3]]), array([[3, 7, 9]])]
Column vectors: 
[array([[5],
        [3]]), 
 array([[0],
        [7]]), 
 array([[3],
        [9]])]
The above output is basically just the returned lists printed with print. 
Only some whitespace is adjusted to make it look nicer. Output is not tested.
"""

import numpy as np

def get_row_vectors(a):
    n, m = a.shape
    # Use np.split to split the matrix a long axis 0 ( rows )
    row_vectors = np.split(a, n)

    return row_vectors

def get_column_vectors(a):
    n, m = a.shape
    # Use np.split to split the matrix a long axis 0 ( rows )
    column_vectors = np.split(a, m, axis = 1)
    return column_vectors

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Row vectors:", get_row_vectors(a))
    print("Column vectors:", get_column_vectors(a))
main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Row vectors: [array([[5, 0, 3, 3]]), array([[7, 9, 3, 5]]), array([[2, 4, 7, 6]]), array([[8, 8, 1, 6]])]
Column vectors: [array([[5],
       [7],
       [2],
       [8]]), array([[0],
       [9],
       [4],
       [8]]), array([[3],
       [3],
       [7],
       [1]]), array([[3],
       [5],
       [6],
       [6]])]
