**Comparisons and Masking in NumPy:**

1. Element-wise Comparison:
   - You can perform element-wise comparisons between NumPy arrays.
   - Example:
     ```python
     a = np.array([1, 3, 4])
     b = np.array([2, 2, 7])
     c = a < b
     ```
     Result: `[True, False, True]`

2. Checking All and Any:
   - You can check if all or any comparisons are True using `all()` and `any()` functions.
   - Example:
     ```python
     print(c.all())  # Check if all comparisons are True (False in this case)
     print(c.any())  # Check if any comparison is True (True in this case)
     ```

3. Counting True Comparisons:
   - You can count the number of True comparisons using `np.sum()` on the boolean array.
   - Example:
     ```python
     print(np.sum(c))  # Count the number of True comparisons (2 in this case)
     ```

4. Broadcasting Rules:
   - Broadcasting rules apply to comparison operations, allowing you to compare arrays of different shapes.
   - Example:
     ```python
     print(a > 0)  # Compare array 'a' with 0 element-wise
     ```

**Using Real Data (Weather Data):**

1. Loading Weather Data:
   - You can use Pandas to load real data, such as daily average temperatures from a CSV file.
   - Example:
     ```python
     import pandas as pd
     a = pd.read_csv("https://raw.githubusercontent.com/csmastersUH/data_analysis_with_python_2020/master/kumpula-weather-2017.csv")['Air temperature (degC)'].values
     ```

2. Counting Days with Temperatures Below Zero:
   - You can count the number of days with temperatures below zero using NumPy.
   - Example:
     ```python
     print("Number of days with the temperature below zero", np.sum(a < 0))
     ```

**Boolean Operations and Masking:**

1. Combining Boolean Values:
   - You can combine boolean values using `and`, `or`, and `not` for core Python.
   - For boolean arrays, use element-wise operators `&`, `|`, and `~`.
   - Example:
     ```python
     np.sum((0 < a) & (a < 10))  # Count temperatures between 0 and 10
     ```

2. Masking:
   - Boolean arrays can be used to select a subset of elements.
   - Example:
     ```python
     c = a > 0
     print(c[:10])  # Print the first ten elements of the boolean array
     print(a[c])    # Select only the positive temperatures from 'a'
     ```

3. Masking to Assign New Values:
   - You can use masking to assign new values to specific elements in an array.
   - Example:
     ```python
     a[~c] = 0  # Zero out the negative temperatures in 'a'
     ```

Make sure to compare the modified array with the original array to understand how masking works.

In [13]:
"""
Exercise 3.1 (column comparison)
Write function column_comparison that gets a two dimensional array as parameter. 
The function should return a new array containing those rows from the input that have 
the value in the second column larger than in the second last column. 
You may assume that the input contains at least two columns. 

Don't use loops, but instead vectorized operations. 
Try out your function in the main function.

For array

 [[8 9 3 8 8]
 [0 5 3 9 9]
 [5 7 6 0 4]
 [7 8 1 6 2]
 [2 1 3 5 8]]
the result would be

 [[8 9 3 8 8]
 [5 7 6 0 4]
 [7 8 1 6 2]]
"""

import numpy as np

def column_comparison(a):
    """
    The function should return a new array containing those rows 
    from the input that have the value in the second column larger than
    in the second last column.
    """
    second_column = a[:,1]
    second_last_column = a[:,-2]

    larger_than_bool = (second_column > second_last_column)
    larger_than_rows = a[larger_than_bool]
   
    return larger_than_rows
"""
def column_comparison(a):
    mask = a[:,1] > a[:,-2]
    return a[mask]
"""
def main():
    matrix = np.array([[8, 9, 3, 8, 8],
                  [0, 5, 3, 9, 9],
                  [5, 7, 6, 0, 4],
                  [7, 8, 1, 6, 2],
                  [2, 1, 3, 5, 8]])
    result=column_comparison(matrix)
    print(result)

main()

[[8 9 3 8 8]
 [5 7 6 0 4]
 [7 8 1 6 2]]


In [19]:
"""
Exercise 3.2 (first half second half)
Write function first_half_second_half that gets a two dimensional array of shape (n,2*m) as a parameter. 
The input array has 2*m columns. 

The output from the function should be a matrix with those rows from the input 
that have the sum of the first m elements larger than the sum of the last m elements on the row. 
Your solution should call the np.sum function or the corresponding method exactly twice.

Example of usage:

a = np.array([[1, 3, 4, 2],
              [2, 2, 1, 2]])
first_half_second_half(a)
array([[2, 2, 1, 2]])
"""


import numpy as np

def first_half_second_half(a):
    n, m = a.shape
    mid = m//2
    first_half = np.sum(a[:, :mid], axis = 1)
    last_half = np.sum(a[:, mid:], axis = 1)

    first_half_larger_row = a[(first_half > last_half)]
    return (first_half_larger_row)
"""
def first_half_second_half(a):
    a1, a2 = np.split(a, 2, axis=1)
    mask = np.sum(a1, axis=1) > np.sum(a2, axis=1)
    return a[mask]
"""
def main():
    a = np.array([[1, 3, 4, 2],
              [2, 2, 1, 2]])
    first_half_second_half(a)
main()

[[2 2 1 2]]
